import { Link } from "react-router-dom";
import { ArrowRight, FileText, Brain, Search, Download, Shield, BarChart3 } from "lucide-react";
import { Button } from "@/components/ui/button";

const features = [
  {
    icon: FileText,
    title: "Upload & Index PDFs",
    description: "Drop your research papers and documents. They're automatically chunked, embedded, and indexed for instant retrieval.",
  },
  {
    icon: Brain,
    title: "AI-Powered Q&A",
    description: "Ask questions about your documents. Get accurate answers with citations, confidence scores, and source tracking.",
  },
  {
    icon: Search,
    title: "Smart Web Fallback",
    description: "When your documents don't have the answer, DocMind automatically searches the web for real-time information.",
  },
  {
    icon: Download,
    title: "Deep Research Reports",
    description: "Submit a topic and receive a comprehensive DOCX research report generated by a multi-step AI agent.",
  },
  {
    icon: Shield,
    title: "Secure & Private",
    description: "Custom JWT authentication, encrypted tokens, and per-user data isolation. Your documents stay yours.",
  },
  {
    icon: BarChart3,
    title: "RAGAS Evaluation",
    description: "Built-in AI quality dashboard measuring faithfulness, relevancy, and context precision of every response.",
  },
];

const techStack = [
  "React", "FastAPI", "LangGraph", "Gemini AI", "ChromaDB", "PostgreSQL", "Tailwind CSS", "Tavily",
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-neutral-950 text-neutral-100">
      {/* Nav */}
      <nav className="flex items-center justify-between px-6 md:px-12 py-4 max-w-7xl mx-auto">
        <div className="flex items-center gap-2">
          <div className="h-8 w-8 rounded-lg bg-primary flex items-center justify-center">
            <Brain className="h-5 w-5 text-white" />
          </div>
          <span className="text-lg font-semibold">DocMind AI</span>
        </div>
        <div className="flex items-center gap-3">
          <Link to="/login">
            <Button variant="ghost" className="text-neutral-300 hover:text-white">
              Log in
            </Button>
          </Link>
          <Link to="/signup">
            <Button className="bg-primary hover:bg-primary/90 text-white rounded-full px-5">
              Get Started — It's Free
            </Button>
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="max-w-7xl mx-auto px-6 md:px-12 pt-16 pb-20 md:pt-24 md:pb-28">
        <div className="grid md:grid-cols-2 gap-12 items-center">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-neutral-800 text-xs text-neutral-300 mb-6">
              <span className="h-1.5 w-1.5 rounded-full bg-green-400" />
              AI Research Assistant
            </div>

            <h1 className="text-5xl md:text-7xl font-bold tracking-tight leading-[1.1] mb-6">
              <span className="text-neutral-100">Research</span>
              <br />
              <span className="bg-gradient-to-r from-primary to-indigo-400 bg-clip-text text-transparent">
                Smarter
              </span>
            </h1>

            <p className="text-lg text-neutral-400 max-w-md mb-8 leading-relaxed">
              Deep insights from your documents and the web.
              <br />
              All powered by one intelligent AI agent.
            </p>

            <div className="flex items-center gap-4">
              <Link to="/signup">
                <Button size="lg" className="bg-primary hover:bg-primary/90 text-white rounded-full px-8 gap-2">
                  Get Started Free
                  <ArrowRight className="h-4 w-4" />
                </Button>
              </Link>
              <Link to="/login" className="text-sm text-neutral-400 hover:text-white underline underline-offset-4">
                Already have an account?
              </Link>
            </div>
          </div>

          {/* Right side — mock UI */}
          <div className="hidden md:block">
            <div className="bg-neutral-900 rounded-2xl border border-neutral-800 p-6 shadow-2xl">
              {/* Mode tabs */}
              <div className="flex gap-2 mb-5">
                <span className="px-4 py-1.5 rounded-full bg-primary/20 text-primary text-sm font-medium border border-primary/30">
                  Q&A Chat
                </span>
                <span className="px-4 py-1.5 rounded-full bg-neutral-800 text-neutral-400 text-sm">
                  Deep Research
                </span>
                <span className="px-4 py-1.5 rounded-full bg-neutral-800 text-neutral-400 text-sm">
                  Admin
                </span>
              </div>

              {/* Mock chat */}
              <div className="space-y-3 mb-4">
                <div className="flex justify-end">
                  <div className="bg-primary text-white text-sm px-4 py-2 rounded-2xl rounded-br-sm max-w-[70%]">
                    How does RAG improve LLM accuracy?
                  </div>
                </div>
                <div className="flex justify-start">
                  <div className="bg-neutral-800 text-neutral-200 text-sm px-4 py-2 rounded-2xl rounded-bl-sm max-w-[80%]">
                    RAG enhances LLMs by grounding responses in external data, reducing hallucination and improving factual accuracy...
                    <div className="flex items-center gap-2 mt-2 pt-2 border-t border-neutral-700">
                      <span className="flex items-center gap-1">
                        <span className="h-1.5 w-1.5 rounded-full bg-green-400" />
                        <span className="h-1.5 w-1.5 rounded-full bg-green-400" />
                        <span className="h-1.5 w-1.5 rounded-full bg-green-400" />
                        <span className="h-1.5 w-1.5 rounded-full bg-neutral-600" />
                        <span className="h-1.5 w-1.5 rounded-full bg-neutral-600" />
                      </span>
                      <span className="text-[10px] text-neutral-500">High confidence</span>
                      <span className="ml-auto text-[10px] px-1.5 py-0.5 rounded bg-neutral-700 text-neutral-400">Documents</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Mock input */}
              <div className="flex gap-2">
                <div className="flex-1 bg-neutral-800 rounded-lg px-4 py-2.5 text-sm text-neutral-500">
                  Ask a question...
                </div>
                <div className="h-10 w-10 rounded-lg bg-primary flex items-center justify-center">
                  <ArrowRight className="h-4 w-4 text-white" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Tech Stack Bar */}
      <section className="border-y border-neutral-800 py-6">
        <div className="max-w-7xl mx-auto px-6 md:px-12 flex flex-wrap items-center justify-center gap-8 md:gap-12">
          {techStack.map((tech) => (
            <span key={tech} className="text-sm text-neutral-500 font-medium tracking-wide">
              {tech}
            </span>
          ))}
        </div>
      </section>

      {/* Features */}
      <section className="max-w-7xl mx-auto px-6 md:px-12 py-20">
        <div className="text-center mb-14">
          <h2 className="text-3xl md:text-4xl font-bold mb-3">Everything you need to research smarter</h2>
          <p className="text-neutral-400 max-w-lg mx-auto">
            Upload documents, ask questions, generate reports — all in one intelligent platform.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature) => (
            <div
              key={feature.title}
              className="bg-neutral-900 border border-neutral-800 rounded-2xl p-6 hover:border-neutral-700 transition-colors"
            >
              <div className="h-10 w-10 rounded-xl bg-primary/10 flex items-center justify-center mb-4">
                <feature.icon className="h-5 w-5 text-primary" />
              </div>
              <h3 className="font-semibold text-lg mb-2">{feature.title}</h3>
              <p className="text-sm text-neutral-400 leading-relaxed">{feature.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="max-w-7xl mx-auto px-6 md:px-12 py-20">
        <div className="bg-gradient-to-br from-primary/20 to-indigo-500/10 border border-primary/20 rounded-3xl p-10 md:p-16 text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Ready to supercharge your research?</h2>
          <p className="text-neutral-400 mb-8 max-w-md mx-auto">
            Start uploading your documents and get AI-powered insights in seconds. Free to use.
          </p>
          <Link to="/signup">
            <Button size="lg" className="bg-primary hover:bg-primary/90 text-white rounded-full px-10 gap-2">
              Get Started Free
              <ArrowRight className="h-4 w-4" />
            </Button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-neutral-800 py-8">
        <div className="max-w-7xl mx-auto px-6 md:px-12 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <Brain className="h-5 w-5 text-primary" />
            <span className="text-sm font-semibold">DocMind AI</span>
          </div>
          <p className="text-xs text-neutral-500">
            Built with React, FastAPI, LangGraph, Gemini AI & ChromaDB
          </p>
          <p className="text-xs text-neutral-500">
            © {new Date().getFullYear()} DocMind AI. Final Year Project.
          </p>
        </div>
      </footer>
    </div>
  );
}
